[package]
name = "mandelbrot"
version = "0.1.0"
# All of the examples in Rust in Action are tested for 2018
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
